// Distinct menu categories dumped from Menu table
// Generated by dump-categories.ts — do not edit by hand.
// Re-run `npx tsx db/dump-categories.ts` whenever Menu categories change.

export const categoriesFromDb = [
  "Beef Fry",
  "Boiled Beef",
  "Bottled Drinks",
  "Cereals",
  "Chicken",
  "Fish",
  "Hot Beverages",
  "Matumbo",
  "Mbuzi Fry",
  "Snacks",
  "Special Meals",
  "Vegetable Plates",
] as const;

export const categorySeedData = categoriesFromDb.map((name) => ({ name }));
