import "dotenv/config";
import { writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import pg from "pg";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "./generated/prisma/client.js";

// Dumps distinct category values from the Menu table into categories-from-db.ts.
// Run on a machine whose DB has the correct categories, then push the output
// file to remote and run `seed-categories` on the restaurant machine.

async function main() {
  const connectionString = `${process.env.DATABASE_URL}`;
  const pool = new pg.Pool({ connectionString });
  const adapter = new PrismaPg(pool);
  const prisma = new PrismaClient({ adapter });

  const rows = await prisma.menu.findMany({
    select: { category: true },
    distinct: ["category"],
    orderBy: { category: "asc" },
  });
  const categories = rows.map((r) => r.category);

  const here = path.dirname(fileURLToPath(import.meta.url));
  const outPath = path.join(here, "categories-from-db.ts");

  const body = categories.map((c) => `  "${c}",`).join("\n");

  const content = `// Distinct menu categories dumped from Menu table
// Generated by dump-categories.ts — do not edit by hand.
// Re-run \`npx tsx db/dump-categories.ts\` whenever Menu categories change.

export const categoriesFromDb = [
${body}
] as const;

export const categorySeedData = categoriesFromDb.map((name) => ({ name }));
`;

  await writeFile(outPath, content, "utf8");
  console.log(`Dumped ${categories.length} categories → ${outPath}`);
  categories.forEach((c) => console.log(`  - ${c}`));

  await pool.end();
}

main();