-- Convert all timestamp columns to timestamptz, preserving existing data.
-- Prisma writes DateTime values as their UTC representation into these
-- "timestamp without time zone" columns, so reinterpreting the stored value
-- with AT TIME ZONE 'UTC' keeps each absolute instant intact (e.g. a stored
-- 02:30 UTC was actually 05:30 in Nairobi local time and stays that instant).

ALTER TABLE "Account" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMP(3) WITH TIME ZONE USING "createdAt" AT TIME ZONE 'UTC';
ALTER TABLE "Account" ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMP(3) WITH TIME ZONE USING "updatedAt" AT TIME ZONE 'UTC';
ALTER TABLE "Cart" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMP(6) WITH TIME ZONE USING "createdAt" AT TIME ZONE 'UTC';
ALTER TABLE "Cart" ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMP(3) WITH TIME ZONE USING "updatedAt" AT TIME ZONE 'UTC';
ALTER TABLE "Category" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMP(6) WITH TIME ZONE USING "createdAt" AT TIME ZONE 'UTC';
ALTER TABLE "Category" ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMP(6) WITH TIME ZONE USING "updatedAt" AT TIME ZONE 'UTC';
ALTER TABLE "CookingRecord" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMP(3) WITH TIME ZONE USING "createdAt" AT TIME ZONE 'UTC';
ALTER TABLE "CookingRecordAssignment" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMP(3) WITH TIME ZONE USING "createdAt" AT TIME ZONE 'UTC';
ALTER TABLE "Department" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMP(3) WITH TIME ZONE USING "createdAt" AT TIME ZONE 'UTC';
ALTER TABLE "Department" ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMP(3) WITH TIME ZONE USING "updatedAt" AT TIME ZONE 'UTC';
ALTER TABLE "DepartmentStockSupply" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMP(3) WITH TIME ZONE USING "createdAt" AT TIME ZONE 'UTC';
ALTER TABLE "Menu" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMP(6) WITH TIME ZONE USING "createdAt" AT TIME ZONE 'UTC';
ALTER TABLE "MenuAccompaniment" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMP(6) WITH TIME ZONE USING "createdAt" AT TIME ZONE 'UTC';
ALTER TABLE "Order" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMP(6) WITH TIME ZONE USING "createdAt" AT TIME ZONE 'UTC';
ALTER TABLE "Order" ALTER COLUMN "deliveredAt" SET DATA TYPE TIMESTAMP(6) WITH TIME ZONE USING "deliveredAt" AT TIME ZONE 'UTC';
ALTER TABLE "Order" ALTER COLUMN "paidAt" SET DATA TYPE TIMESTAMP(6) WITH TIME ZONE USING "paidAt" AT TIME ZONE 'UTC';
ALTER TABLE "Order" ALTER COLUMN "voidedAt" SET DATA TYPE TIMESTAMP(6) WITH TIME ZONE USING "voidedAt" AT TIME ZONE 'UTC';
ALTER TABLE "Review" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMP(6) WITH TIME ZONE USING "createdAt" AT TIME ZONE 'UTC';
ALTER TABLE "Session" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMP(6) WITH TIME ZONE USING "createdAt" AT TIME ZONE 'UTC';
ALTER TABLE "Session" ALTER COLUMN "expires" SET DATA TYPE TIMESTAMP(6) WITH TIME ZONE USING "expires" AT TIME ZONE 'UTC';
ALTER TABLE "Session" ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMP(3) WITH TIME ZONE USING "updatedAt" AT TIME ZONE 'UTC';
ALTER TABLE "Shift" ALTER COLUMN "actualCloseTime" SET DATA TYPE TIMESTAMP(6) WITH TIME ZONE USING "actualCloseTime" AT TIME ZONE 'UTC';
ALTER TABLE "Shift" ALTER COLUMN "actualOpeningTime" SET DATA TYPE TIMESTAMP(6) WITH TIME ZONE USING "actualOpeningTime" AT TIME ZONE 'UTC';
ALTER TABLE "Shift" ALTER COLUMN "autoCloseTime" SET DATA TYPE TIMESTAMP(3) WITH TIME ZONE USING "autoCloseTime" AT TIME ZONE 'UTC';
ALTER TABLE "Shift" ALTER COLUMN "autoClosedAt" SET DATA TYPE TIMESTAMP(6) WITH TIME ZONE USING "autoClosedAt" AT TIME ZONE 'UTC';
ALTER TABLE "Shift" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMP(6) WITH TIME ZONE USING "createdAt" AT TIME ZONE 'UTC';
ALTER TABLE "Shift" ALTER COLUMN "finalClosedAt" SET DATA TYPE TIMESTAMP(6) WITH TIME ZONE USING "finalClosedAt" AT TIME ZONE 'UTC';
ALTER TABLE "Shift" ALTER COLUMN "openingTime" SET DATA TYPE TIMESTAMP(3) WITH TIME ZONE USING "openingTime" AT TIME ZONE 'UTC';
ALTER TABLE "ShiftSnapshot" ALTER COLUMN "autoCloseTime" SET DATA TYPE TIMESTAMP(6) WITH TIME ZONE USING "autoCloseTime" AT TIME ZONE 'UTC';
ALTER TABLE "ShiftSnapshot" ALTER COLUMN "manualCloseTime" SET DATA TYPE TIMESTAMP(6) WITH TIME ZONE USING "manualCloseTime" AT TIME ZONE 'UTC';
ALTER TABLE "StockFulfillment" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMP(3) WITH TIME ZONE USING "createdAt" AT TIME ZONE 'UTC';
ALTER TABLE "StockFulfillmentItem" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMP(3) WITH TIME ZONE USING "createdAt" AT TIME ZONE 'UTC';
ALTER TABLE "StockRequest" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMP(3) WITH TIME ZONE USING "createdAt" AT TIME ZONE 'UTC';
ALTER TABLE "StockRequest" ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMP(3) WITH TIME ZONE USING "updatedAt" AT TIME ZONE 'UTC';
ALTER TABLE "StockRequestItem" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMP(3) WITH TIME ZONE USING "createdAt" AT TIME ZONE 'UTC';
ALTER TABLE "StockRequestItem" ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMP(3) WITH TIME ZONE USING "updatedAt" AT TIME ZONE 'UTC';
ALTER TABLE "StockSupply" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMP(3) WITH TIME ZONE USING "createdAt" AT TIME ZONE 'UTC';
ALTER TABLE "StockSupply" ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMP(3) WITH TIME ZONE USING "updatedAt" AT TIME ZONE 'UTC';
ALTER TABLE "User" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMP(6) WITH TIME ZONE USING "createdAt" AT TIME ZONE 'UTC';
ALTER TABLE "User" ALTER COLUMN "emailVerified" SET DATA TYPE TIMESTAMP(6) WITH TIME ZONE USING "emailVerified" AT TIME ZONE 'UTC';
ALTER TABLE "User" ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMP(3) WITH TIME ZONE USING "updatedAt" AT TIME ZONE 'UTC';
ALTER TABLE "VerificationToken" ALTER COLUMN "expires" SET DATA TYPE TIMESTAMP(3) WITH TIME ZONE USING "expires" AT TIME ZONE 'UTC';